### ISSUE TITLE
Some malware or bullshit, idk.

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [XKaguya/ShowAmmo#1]
I have an issue with this mod:
* It doesn't work.

**Comment by XKaguya** [comment]
> I have an issue with this mod:
> 
> * It doesn't work.

Please give me the log and the profile code so that i can test what happened.
And i believe the issue was caused by language. What's your Language ?

**Comment by XKaguya** [comment]
Close this issue due to no response. If have any question welcome to reopen.
