### ISSUE TITLE
I don't see the ammo count. Where are they?

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [XKaguya/ShowAmmo#2]
Where is the ammo count?I have attached logs below

My game is in English language
[Player.log](https://github.com/user-attachments/files/16011597/Player.log)

**Comment by XKaguya** [comment]
> Where is the ammo count?I have attached logs below
> 
> My game is in English language [Player.log](https://github.com/user-attachments/files/16011597/Player.log)

Did you changed the Settings about language to English ? The default language setting is Chinese, You should set to 0 for English
And what will happen if u pressed the key

I dont see any error in your logs

**Comment by XKaguya** [comment]
Close this issue due to no response. If have any question welcome to reopen.
